"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pdfConverterGui.py']
APP_NAME = 'Pdf Converter % Data Analyzer'
DATA_FILES = []
OPTIONS = {}

setup(
    name = APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'openpyxl'],
)
